name: Deploy Vite App to cPanel via SSH

on:
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Install Dependencies & Build
        run: |
          npm install
          npm run build

      - name: Setup SSH
        run: |
          mkdir -p ~/.ssh
          echo "${{ secrets.SSH_PRIVATE_KEY }}" > ~/.ssh/id_rsa
          chmod 600 ~/.ssh/id_rsa
          ssh-keyscan -p ${{ secrets.SSH_PORT }} -H ${{ secrets.SSH_HOST }} >> ~/.ssh/known_hosts

      - name: Zip and Upload Build
        run: |
          zip -r dist.zip dist
          scp -P ${{ secrets.SSH_PORT }} -i ~/.ssh/id_rsa dist.zip ${{ secrets.SSH_USERNAME }}@${{ secrets.SSH_HOST }}:${{ secrets.REMOTE_DIR }}

      - name: Unzip and Deploy
        run: |
          ssh -p ${{ secrets.SSH_PORT }} -i ~/.ssh/id_rsa ${{ secrets.SSH_USERNAME }}@${{ secrets.SSH_HOST }} << EOF
            unzip -o ${REMOTE_DIR}/dist.zip -d ${REMOTE_DIR}
            rm ${REMOTE_DIR}/dist.zip
            echo "✅ Deployment completed"
          EOF
