name: Deploy Vite Source Code to cPanel via SSH

on:
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup SSH
        run: |
          mkdir -p ~/.ssh
          echo "${{ secrets.SSH_PRIVATE_KEY }}" > ~/.ssh/id_rsa
          chmod 600 ~/.ssh/id_rsa
          ssh-keyscan -p ${{ secrets.SSH_PORT }} -H ${{ secrets.SSH_HOST }} >> ~/.ssh/known_hosts

      - name: Zip source code (exclude node_modules and .git)
        run: |
          zip -r app.zip . -x "node_modules/*" ".git/*"

      - name: Upload to server
        run: |
          scp -P ${{ secrets.SSH_PORT }} -i ~/.ssh/id_rsa app.zip ${{ secrets.SSH_USERNAME }}@${{ secrets.SSH_HOST }}:${{ secrets.REMOTE_DIR }}

      - name: Unzip and build on server
        run: |
          ssh -p ${{ secrets.SSH_PORT }} -i ~/.ssh/id_rsa ${{ secrets.SSH_USERNAME }}@${{ secrets.SSH_HOST }} << EOF
            cd ${{ secrets.REMOTE_DIR }}
            unzip -o app.zip
            rm app.zip
            npm install
            npm run build
            echo "✅ Build completed on server"
          EOF
